
import type { DarkTimesData, ObserverFormData, DarkTimeWindow, TimeRangeFilter } from '@/types';
import { formatDate, formatNumber, formatTime12Hour } from './dateUtils';

/**
 * Filter information for CSV export
 */
export interface FilterInfo {
  minDurationHours?: number;
  selectedTypes: Set<DarkTimeWindow['type']>;
  hideEmptyDays: boolean;
  timeRangeFilter?: TimeRangeFilter;
}

/**
 * Exports dark times data to CSV format
 * @param darkTimes - Dark times calculation results
 * @param timezone - IANA timezone identifier for formatting
 * @param formData - User input data (observer location, dates, etc.)
 * @param filename - Output filename
 * @param exportMinimal - If true, only export dark sky windows (no metadata)
 * @param filterInfo - Active filter settings
 */
export function exportTableToCSV(
  darkTimes: DarkTimesData,
  timezone: string,
  formData: ObserverFormData,
  filename: string = 'dark_times_export.csv',
  exportMinimal: boolean = false,
  filterInfo?: FilterInfo
): void {
  const csv: string[] = [];

  // Attribution block
  csv.push('# Data generated by the darkSky web app');
  csv.push('# Website: https://bobhampton.github.io/darkSky/');
  csv.push('# GitHub: https://github.com/bobhampton/darkSky');
  csv.push('# DOI: https://doi.org/10.5281/zenodo.14847872');
  csv.push('# If you use this data in published research please cite the project using the DOI above.');
  csv.push(''); // spacer row

  // User inputs
  csv.push('User inputs:');
  csv.push(`Observer Latitude:,${formData.latitude}`);
  csv.push(`Observer Longitude:,${formData.longitude}`);
  csv.push(`Elevation (meters):,${formData.elevation}`);
  csv.push(`Date Range:,${formData.dateStart} to ${formData.dateEnd}`);
  csv.push(`Output Time Zone:,${timezone}`);
  csv.push('');

  // Active filters information
  if (filterInfo) {
    csv.push('Active Filters:');
    
    // Duration filter
    if (filterInfo.minDurationHours && filterInfo.minDurationHours > 0) {
      csv.push(`Minimum Duration:,≥ ${filterInfo.minDurationHours} hours`);
    } else {
      csv.push(`Minimum Duration:,None`);
    }
    
    // Time range filter
    if (filterInfo.timeRangeFilter && filterInfo.timeRangeFilter.enabled) {
      const startTime = formatTime12Hour(filterInfo.timeRangeFilter.startTime);
      const endTime = formatTime12Hour(filterInfo.timeRangeFilter.endTime);
      csv.push(`Time Range Filter:,"${startTime} - ${endTime}"`);
    } else {
      csv.push(`Time Range Filter:,None`);
    }
    
    // Type filter
    const allTypes: DarkTimeWindow['type'][] = ['dawn', 'dusk', 'polarNight'];
    const selectedCount = filterInfo.selectedTypes.size;
    if (selectedCount === allTypes.length) {
      csv.push(`Window Types:,All types (Dawn, Dusk, Polar Night)`);
    } else if (selectedCount > 0) {
      const typeNames = Array.from(filterInfo.selectedTypes).map(t => 
        t === 'polarNight' ? 'Polar Night' : t.charAt(0).toUpperCase() + t.slice(1)
      );
      csv.push(`Window Types:,"${typeNames.join(', ')} only"`);
    } else {
      csv.push(`Window Types:,None (no windows exported)`);
    }
    
    // Hide empty days filter
    csv.push(`Hide Empty Days:,${filterInfo.hideEmptyDays ? 'Yes' : 'No'}`);
    csv.push('');
  }

  // Define headers
  const baseHeaders = [
    'Date (YYYY-MM-DD)',
    'Dark Time Start (Dawn)',
    'Dark Time End (Dawn)',
    'Dark Time Start (Dusk)',
    'Dark Time End (Dusk)',
  ];

  const extraHeaders = [
    'Moon Rise',
    'Moon Set',
    'Moon Altitude @ 00:00:00',
    'Moon Altitude @ Astronomical Twilight Start',
    'Astronomical Twilight Start',
    'Astronomical Twilight End',
    'Moon Altitude @ Astronomical Twilight End',
    'Moon Altitude @ 23:59:59',
  ];

  csv.push([...baseHeaders, ...(exportMinimal ? [] : extraHeaders)].join(','));

  // Sort dates
  const dates = Object.keys(darkTimes).sort();

  for (const date of dates) {
    const windows = darkTimes[date];
    
    // Filter out metaOnly entries
    const dawnWindows = windows.filter((w) => w.type === 'dawn');
    const duskWindows = windows.filter((w) => w.type === 'dusk');
    const polarNight = windows.find((w) => w.type === 'polarNight');
    const metaOnly = windows.find((w) => w.type === 'metaOnly');

    let dawnStart = '';
    let dawnEnd = '';
    let duskStart = '';
    let duskEnd = '';

    // Get metadata (prefer dawn, fallback to dusk, then metaOnly)
    const meta = dawnWindows[0]?.meta || duskWindows[0]?.meta || metaOnly?.meta;

    // Handle polar night days
    if (polarNight) {
      dawnStart = '00:00:00';
      dawnEnd = '---';
      duskStart = '---';
      duskEnd = '23:59:59';
    } else {
      // Normal dawn/dusk windows
      if (dawnWindows.length > 0) {
        dawnStart = formatDate(dawnWindows[0].start, timezone);
        dawnEnd = formatDate(dawnWindows[0].end, timezone);
      }

      if (duskWindows.length > 0) {
        duskStart = formatDate(duskWindows[0].start, timezone);
        duskEnd = formatDate(duskWindows[0].end, timezone);
      }
    }

    // Build basic row data
    const basicData = [date, dawnStart, dawnEnd, duskStart, duskEnd];

    // Escape CSV values
    const escapedBasicData = basicData.map((text) => {
      const cleaned = text.replace(/"/g, '""');
      return cleaned.includes(',') ? `"${cleaned}"` : cleaned;
    });

    const rowData = [...escapedBasicData];

    // Add extra metadata if not minimal export
    if (!exportMinimal && meta) {
      const fmtNum = (num: number | null | undefined) => formatNumber(num, 2, '');
      const fmtArray = (arr: Date[]) => (arr.length > 0 ? arr.map(d => formatDate(d, timezone)).join('; ') : '');

      rowData.push(
        fmtArray(meta.moonRises),
        fmtArray(meta.moonSets),
        fmtNum(meta.moonAltStartDay),
        fmtNum(meta.moonAltEndNight),
        fmtArray(meta.astronomicalNightEnds),
        fmtArray(meta.astronomicalNightStarts),
        fmtNum(meta.moonAltStartNight),
        fmtNum(meta.moonAltEndDay)
      );
    }

    csv.push(rowData.join(','));
  }

  // Trigger download
  downloadCSV(csv.join('\n'), filename);
}

/**
 * Triggers a browser download of CSV content
 * @param content - CSV content as string
 * @param filename - Filename for download
 */
function downloadCSV(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.display = 'none';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up the URL object
  window.URL.revokeObjectURL(url);
}
